name: leapstartai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.5
  glass_kit: ^4.0.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint:
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

flutter:
  uses-material-design: true
